//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileUpload.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 © 2025 文件上传系统.Powered by LUX EAP TEAM. All rights reserved. 的本地化字符串。
        /// </summary>
        internal static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个基于 .NET 6.0 Windows Forms 的文件上传应用程序 的本地化字符串。
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要功能:
        ///
        ///✓ 可以传图片 的本地化字符串。
        /// </summary>
        internal static string About_Features {
            get {
                return ResourceManager.GetString("About_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传系统 的本地化字符串。
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本: 2.0 的本地化字符串。
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About_WindowTitle {
            get {
                return ResourceManager.GetString("About_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string AboutForm_Title {
            get {
                return ResourceManager.GetString("AboutForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        internal static string Button_AddFolder {
            get {
                return ResourceManager.GetString("Button_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空日志 的本地化字符串。
        /// </summary>
        internal static string Button_ClearLog {
            get {
                return ResourceManager.GetString("Button_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除文件夹 的本地化字符串。
        /// </summary>
        internal static string Button_RemoveFolder {
            get {
                return ResourceManager.GetString("Button_RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始任务 的本地化字符串。
        /// </summary>
        internal static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止任务 的本地化字符串。
        /// </summary>
        internal static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化时自动隐藏到托盘 的本地化字符串。
        /// </summary>
        internal static string CheckBox_MinimizeToTray {
            get {
                return ResourceManager.GetString("CheckBox_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到OK/NG时保留目录结构 的本地化字符串。
        /// </summary>
        internal static string CheckBox_PreserveDirectory {
            get {
                return ResourceManager.GetString("CheckBox_PreserveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递归扫描子文件夹（扫描所有嵌套目录） 的本地化字符串。
        /// </summary>
        internal static string CheckBox_ScanSubfolders {
            get {
                return ResourceManager.GetString("CheckBox_ScanSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用系统托盘功能 的本地化字符串。
        /// </summary>
        internal static string CheckBox_SystemTrayEnabled {
            get {
                return ResourceManager.GetString("CheckBox_SystemTrayEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问用户 的本地化字符串。
        /// </summary>
        internal static string CloseAction_Ask {
            get {
                return ResourceManager.GetString("CloseAction_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接退出 的本地化字符串。
        /// </summary>
        internal static string CloseAction_Exit {
            get {
                return ResourceManager.GetString("CloseAction_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化到托盘 的本地化字符串。
        /// </summary>
        internal static string CloseAction_Minimize {
            get {
                return ResourceManager.GetString("CloseAction_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置信息 的本地化字符串。
        /// </summary>
        internal static string Config_Title {
            get {
                return ResourceManager.GetString("Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置 的本地化字符串。
        /// </summary>
        internal static string ConfigForm_Title {
            get {
                return ResourceManager.GetString("ConfigForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传系统 的本地化字符串。
        /// </summary>
        internal static string Form_Title {
            get {
                return ResourceManager.GetString("Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传系统 v2.0 的本地化字符串。
        /// </summary>
        internal static string Form_WindowTitle {
            get {
                return ResourceManager.GetString("Form_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片压缩配置 的本地化字符串。
        /// </summary>
        internal static string Group_ImageCompression {
            get {
                return ResourceManager.GetString("Group_ImageCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统托盘配置 的本地化字符串。
        /// </summary>
        internal static string Group_SystemTray {
            get {
                return ResourceManager.GetString("Group_SystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程池配置 的本地化字符串。
        /// </summary>
        internal static string Group_ThreadPool {
            get {
                return ResourceManager.GetString("Group_ThreadPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许的文件后缀: 的本地化字符串。
        /// </summary>
        internal static string Label_AllowedExtensions {
            get {
                return ResourceManager.GetString("Label_AllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭窗口时的行为: 的本地化字符串。
        /// </summary>
        internal static string Label_CloseAction {
            get {
                return ResourceManager.GetString("Label_CloseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩质量（1-100，值越小压缩率越高）: 的本地化字符串。
        /// </summary>
        internal static string Label_CompressionQuality {
            get {
                return ResourceManager.GetString("Label_CompressionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩阈值（KB，大于此值将压缩）: 的本地化字符串。
        /// </summary>
        internal static string Label_CompressionThreshold {
            get {
                return ResourceManager.GetString("Label_CompressionThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编号： 的本地化字符串。
        /// </summary>
        internal static string Label_DeviceId {
            get {
                return ResourceManager.GetString("Label_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编号: 的本地化字符串。
        /// </summary>
        internal static string Label_DeviceIdConfig {
            get {
                return ResourceManager.GetString("Label_DeviceIdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用图片压缩（自动压缩大图片） 的本地化字符串。
        /// </summary>
        internal static string Label_EnableImageCompression {
            get {
                return ResourceManager.GetString("Label_EnableImageCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用系统托盘功能 的本地化字符串。
        /// </summary>
        internal static string Label_EnableSystemTray {
            get {
                return ResourceManager.GetString("Label_EnableSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用线程池（用于并发处理大量文件） 的本地化字符串。
        /// </summary>
        internal static string Label_EnableThreadPool {
            get {
                return ResourceManager.GetString("Label_EnableThreadPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败数： 的本地化字符串。
        /// </summary>
        internal static string Label_Failed {
            get {
                return ResourceManager.GetString("Label_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大重试次数: 的本地化字符串。
        /// </summary>
        internal static string Label_MaxRetryCount {
            get {
                return ResourceManager.GetString("Label_MaxRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化时自动隐藏到托盘 的本地化字符串。
        /// </summary>
        internal static string Label_MinimizeToTray {
            get {
                return ResourceManager.GetString("Label_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析规则： 的本地化字符串。
        /// </summary>
        internal static string Label_ParseRule {
            get {
                return ResourceManager.GetString("Label_ParseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到OK/NG时保留目录结构 的本地化字符串。
        /// </summary>
        internal static string Label_PreserveDirectoryStructure {
            get {
                return ResourceManager.GetString("Label_PreserveDirectoryStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时时间(秒): 的本地化字符串。
        /// </summary>
        internal static string Label_RequestTimeout {
            get {
                return ResourceManager.GetString("Label_RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件扫描间隔(秒): 的本地化字符串。
        /// </summary>
        internal static string Label_ScanInterval {
            get {
                return ResourceManager.GetString("Label_ScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递归扫描子文件夹（扫描所有嵌套目录） 的本地化字符串。
        /// </summary>
        internal static string Label_ScanSubfolders {
            get {
                return ResourceManager.GetString("Label_ScanSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功数： 的本地化字符串。
        /// </summary>
        internal static string Label_Success {
            get {
                return ResourceManager.GetString("Label_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程池大小（并发数量）: 的本地化字符串。
        /// </summary>
        internal static string Label_ThreadPoolSize {
            get {
                return ResourceManager.GetString("Label_ThreadPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总文件： 的本地化字符串。
        /// </summary>
        internal static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传接口： 的本地化字符串。
        /// </summary>
        internal static string Label_UploadUrl {
            get {
                return ResourceManager.GetString("Label_UploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传接口URL: 的本地化字符串。
        /// </summary>
        internal static string Label_UploadUrlConfig {
            get {
                return ResourceManager.GetString("Label_UploadUrlConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控文件夹： 的本地化字符串。
        /// </summary>
        internal static string Label_WatchFolder {
            get {
                return ResourceManager.GetString("Label_WatchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控文件夹列表: 的本地化字符串。
        /// </summary>
        internal static string Label_WatchFolders {
            get {
                return ResourceManager.GetString("Label_WatchFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控文件夹列表: 的本地化字符串。
        /// </summary>
        internal static string Label_WatchFoldersList {
            get {
                return ResourceManager.GetString("Label_WatchFoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志信息 的本地化字符串。
        /// </summary>
        internal static string Log_Title {
            get {
                return ResourceManager.GetString("Log_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string Menu_Config {
            get {
                return ResourceManager.GetString("Menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(&amp;X) 的本地化字符串。
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(&amp;H) 的本地化字符串。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置已保存成功！
        ///
        ///是否立即重启程序以使配置生效？ 的本地化字符串。
        /// </summary>
        internal static string Message_ConfigSaved {
            get {
                return ResourceManager.GetString("Message_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置已保存 的本地化字符串。
        /// </summary>
        internal static string Message_ConfigSavedTitle {
            get {
                return ResourceManager.GetString("Message_ConfigSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Message_Confirm {
            get {
                return ResourceManager.GetString("Message_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件夹已在监控列表中 的本地化字符串。
        /// </summary>
        internal static string Message_FolderExists {
            get {
                return ResourceManager.GetString("Message_FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Message_Info {
            get {
                return ResourceManager.GetString("Message_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否最小化到系统托盘?
        ///
        ///点击&quot;是&quot;最小化到托盘
        ///点击&quot;否&quot;退出程序 的本地化字符串。
        /// </summary>
        internal static string Message_MinimizeToTray {
            get {
                return ResourceManager.GetString("Message_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置 的本地化字符串。
        /// </summary>
        internal static string Message_NotConfigured {
            get {
                return ResourceManager.GetString("Message_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择要移除的文件夹 的本地化字符串。
        /// </summary>
        internal static string Message_SelectFolder {
            get {
                return ResourceManager.GetString("Message_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未运行 的本地化字符串。
        /// </summary>
        internal static string Status_NotRunning {
            get {
                return ResourceManager.GetString("Status_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中 的本地化字符串。
        /// </summary>
        internal static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级配置 的本地化字符串。
        /// </summary>
        internal static string Tab_Advanced {
            get {
                return ResourceManager.GetString("Tab_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本配置 的本地化字符串。
        /// </summary>
        internal static string Tab_Basic {
            get {
                return ResourceManager.GetString("Tab_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性能优化 的本地化字符串。
        /// </summary>
        internal static string Tab_Performance {
            get {
                return ResourceManager.GetString("Tab_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        internal static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已最小化到系统托盘 的本地化字符串。
        /// </summary>
        internal static string Tray_MinimizedMessage {
            get {
                return ResourceManager.GetString("Tray_MinimizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置 的本地化字符串。
        /// </summary>
        internal static string Tray_OpenConfig {
            get {
                return ResourceManager.GetString("Tray_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示主窗口 的本地化字符串。
        /// </summary>
        internal static string Tray_ShowMainWindow {
            get {
                return ResourceManager.GetString("Tray_ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始任务 的本地化字符串。
        /// </summary>
        internal static string Tray_StartTask {
            get {
                return ResourceManager.GetString("Tray_StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止任务 的本地化字符串。
        /// </summary>
        internal static string Tray_StopTask {
            get {
                return ResourceManager.GetString("Tray_StopTask", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 界面语言: 的本地化字符串。
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 中文简体 的本地化字符串。
        /// </summary>
        internal static string Language_ChineseSimplified {
            get {
                return ResourceManager.GetString("Language_ChineseSimplified", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 繁体中文 的本地化字符串。
        /// </summary>
        internal static string Language_ChineseTraditional {
            get {
                return ResourceManager.GetString("Language_ChineseTraditional", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        internal static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Tiếng Việt 的本地化字符串。
        /// </summary>
        internal static string Language_Vietnamese {
            get {
                return ResourceManager.GetString("Language_Vietnamese", resourceCulture);
            }
        }
    }
}
